[project]
name = "rooproxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.3",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "uvicorn>=0.40.0",
]
